spring.grpc.client.channel.factstore.keepalive.time=310
spring.grpc.client.channel.factstore.keepalive.without-calls=true
spring.grpc.client.channel.factstore.target=localhost:9090
factcast.grpc.client.id=ec1
mongodb.local.host=localhost
mongodb.local.port=27017