= Concepts
:toc: left
:icons: font



In order to use `FactCast` effectively it is necessary to have an overview of the concepts and to understand
how `FactCast` might differ from other solutions you are already familiar with. So let's take a look at the basics:

=== Write (publish)

With `FactCast` you can _publish_ `Facts` which will be written into a log. You can publish a single `Fact` as well as a
list of `Facts` atomically (all-or-none).

With optimistic locking you can use conditional publishing, which is based upon aggregates that do not change during the
lifecycle of the lock (see xref:../Usage/lowlevel/java/optimistic-locking.adoc[optimistic locking]).

=== Read (subscribe)

In order to receive `Facts` you have to subscribe to `FactCast` with a subscription request. This is where `FactCast`
significantly differs from other solutions because the subscription request contains the _full specification_ of what
events to receive. This means that no server-side administration is needed, nor any prior knowledge about the streams
where to publish the `Facts` into.
