@startuml

title __FACTCAST-CORE's Class Diagram__\n

  namespace org.factcast.core {
    class org.factcast.core.DefaultFact {
    }
  }
  

  namespace org.factcast.core {
    class org.factcast.core.DefaultFactCast {
    }
  }
  

  namespace org.factcast.core {
    interface org.factcast.core.Fact {
    }
  }
  

  namespace org.factcast.core {
    interface org.factcast.core.FactCast {
    }
  }
  

  namespace org.factcast.core {
    class org.factcast.core.FactHeader {
    }
  }
  

  namespace org.factcast.core {
    class org.factcast.core.FactValidation {
    }
  }
  

  namespace org.factcast.core {
    class org.factcast.core.FactValidationException {
    }
  }
  

  namespace org.factcast.core {
    class org.factcast.core.MaxRetryAttemptsExceededException {
    }
  }
  

  namespace org.factcast.core {
    interface org.factcast.core.ReadFactCast {
    }
  }
  

  namespace org.factcast.core {
    class org.factcast.core.Retry {
    }
  }
  

  namespace org.factcast.core {
    namespace lock {
      interface org.factcast.core.lock.Attempt {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace lock {
      class org.factcast.core.lock.AttemptAbortedException {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace lock {
      class org.factcast.core.lock.ExceptionAfterPublish {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace lock {
      class org.factcast.core.lock.IntermediatePublishResult {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace lock {
      class org.factcast.core.lock.LockedOperationBuilder {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace lock {
      class org.factcast.core.lock.PublishingResult {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace lock {
      class org.factcast.core.lock.WithOptimisticLock {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace snap {
      class org.factcast.core.snap.FactCastSnapshotRepository {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace snap {
      class org.factcast.core.snap.Snapshot {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace snap {
      class org.factcast.core.snap.SnapshotId {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace snap {
      interface org.factcast.core.snap.SnapshotRepository {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace spec {
      class org.factcast.core.spec.FactSpec {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace spec {
      class org.factcast.core.spec.FactSpecCoordinates {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace spec {
      class org.factcast.core.spec.FactSpecMatcher {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace spec {
      class org.factcast.core.spec.FilterScript {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace spec {
      class org.factcast.core.spec.JavaScriptEngineSupplier {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace spec {
      interface org.factcast.core.spec.Specification {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      abstract class org.factcast.core.store.AbstractFactStore {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      interface org.factcast.core.store.FactStore {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      class org.factcast.core.store.RetryableException {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      class org.factcast.core.store.StateToken {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      interface org.factcast.core.store.TokenStore {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      interface org.factcast.core.subscription.FactTransformerService {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      interface org.factcast.core.subscription.FactTransformers {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      interface org.factcast.core.subscription.FactTransformersFactory {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      class org.factcast.core.subscription.FluentSubscriptionRequest {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      class org.factcast.core.subscription.ReconnectingFactSubscriptionWrapper {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      interface org.factcast.core.subscription.SpecBuilder {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      interface org.factcast.core.subscription.Subscription {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      class org.factcast.core.subscription.SubscriptionCancelledException {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      class org.factcast.core.subscription.SubscriptionImpl {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      interface org.factcast.core.subscription.SubscriptionRequest {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      class org.factcast.core.subscription.SubscriptionRequestTO {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      class org.factcast.core.subscription.TransformationException {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      namespace observer {
        interface org.factcast.core.subscription.observer.FactObserver {
        }
      }
    }
  }
  

  namespace org.factcast.core {
    namespace subscription {
      namespace observer {
        interface org.factcast.core.subscription.observer.GenericObserver {
        }
      }
    }
  }
  

  namespace org.factcast.core {
    namespace util {
      class org.factcast.core.util.ExceptionHelper {
      }
    }
  }
  

  namespace org.factcast.core {
    namespace util {
      class org.factcast.core.util.FactCastJson {
      }
    }
  }
  

  org.factcast.core.DefaultFact .up.|> java.io.Externalizable
  org.factcast.core.DefaultFact .up.|> org.factcast.core.Fact
  org.factcast.core.DefaultFact o-- org.factcast.core.FactHeader : deserializedHeader
  org.factcast.core.DefaultFactCast .up.|> org.factcast.core.FactCast
  org.factcast.core.DefaultFactCast o-- org.factcast.core.store.FactStore : store
  org.factcast.core.lock.LockedOperationBuilder o-- org.factcast.core.store.FactStore : store
  org.factcast.core.lock.WithOptimisticLock o-- org.factcast.core.store.FactStore : store
  org.factcast.core.snap.FactCastSnapshotRepository .up.|> org.factcast.core.snap.SnapshotRepository
  org.factcast.core.snap.FactCastSnapshotRepository o-- org.factcast.core.store.FactStore : store
  org.factcast.core.snap.Snapshot o-- org.factcast.core.snap.SnapshotId : id
  org.factcast.core.spec.FactSpec o-- org.factcast.core.spec.FilterScript : filterScript
  org.factcast.core.spec.FactSpecMatcher .up.|> java.util.function.Predicate
  org.factcast.core.spec.FactSpecMatcher o-- org.factcast.core.spec.FilterScript : script
  org.factcast.core.spec.JavaScriptEngineSupplier .up.|> java.util.function.Supplier
  org.factcast.core.store.AbstractFactStore .up.|> org.factcast.core.store.FactStore
  org.factcast.core.store.AbstractFactStore o-- org.factcast.core.store.TokenStore : tokenStore
  org.factcast.core.subscription.FluentSubscriptionRequest .up.|> org.factcast.core.subscription.SubscriptionRequest
  org.factcast.core.subscription.ReconnectingFactSubscriptionWrapper .up.|> org.factcast.core.subscription.Subscription
  org.factcast.core.subscription.ReconnectingFactSubscriptionWrapper o-- org.factcast.core.subscription.observer.FactObserver : observer
  org.factcast.core.subscription.ReconnectingFactSubscriptionWrapper o-- org.factcast.core.subscription.observer.FactObserver : originalObserver
  org.factcast.core.subscription.ReconnectingFactSubscriptionWrapper o-- org.factcast.core.subscription.SubscriptionRequestTO : originalRequest
  org.factcast.core.subscription.ReconnectingFactSubscriptionWrapper o-- org.factcast.core.store.FactStore : store
  org.factcast.core.subscription.SubscriptionImpl .up.|> org.factcast.core.subscription.Subscription
  org.factcast.core.subscription.SubscriptionImpl o-- org.factcast.core.subscription.FactTransformers : transformers
  org.factcast.core.subscription.SubscriptionRequestTO .up.|> org.factcast.core.subscription.SubscriptionRequest


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
