codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: up
  range: "80...100"

  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "**/src/test/**/*.java"
  - "**/src/java/**/*Configuration.java"
  - "**/src/java/**/*Exception.java"
  - "**/src/java/**/*Helper.java"
  - "**/src/java/**/*Properties.java"
  - "**/org/factcast/test/**/*.java"
  - "**/factcast-examples/**/*.java"
  - "**/src/test/**/*.kt"
  - "**/org/factcast/test/**/*.kt"

