services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: