version: '3.2'
services:

  factcast:
    image: factcast/factcast
    ports:
      - "9443:9443"
    environment:
      spring.datasource.url: 'jdbc:postgresql://db/fc?user=fc&password=fc'
    volumes:
      - ./config:/config
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: fc
      POSTGRES_USER: fc
      POSTGRES_DB: fc
    ports:
      - "5432:5432"


      