@startuml

title __PAGED's Class Diagram__\n

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        namespace paged {
          class org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory {
              - jdbc : JdbcTemplate
              + PgPagedCatchUpFactory()
              + create()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        namespace paged {
          class org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup {
              - clientId : long
              - jdbc : JdbcTemplate
              {static} - log : Logger
              - serial : AtomicLong
              + PgPagedCatchup()
              + run()
              - doFetch()
          }
        }
      }
    }
  }
  

  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory .up.|> org.factcast.store.pgsql.internal.catchup.PgCatchupFactory
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory o-- org.factcast.store.pgsql.PgConfigurationProperties : props
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory o-- org.factcast.store.pgsql.internal.query.PgFactIdToSerialMapper : serMapper
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup .up.|> org.factcast.store.pgsql.internal.catchup.PgCatchup
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.store.pgsql.internal.PgPostQueryMatcher : postQueryMatcher
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.store.pgsql.PgConfigurationProperties : props
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.core.subscription.SubscriptionRequestTO : request
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.core.subscription.SubscriptionImpl : subscription


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
