@startuml

title __FACTCAST-SERVER-GRPC's Class Diagram__\n

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.BlockingStreamObserver {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.FactCastGrpcServerConfiguration {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.FactCastSecretProperties {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.FactCastSecurityConfiguration {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.FactStoreGrpcService {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.FactcastRemoteException {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.GrpcCompressionInterceptor {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.GrpcExceptionInterceptor {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.GrpcLimitProperties {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.GrpcObserverAdapter {
    }
  }
  

  namespace org.factcast.server.grpc {
    class org.factcast.server.grpc.TransportLayerException {
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace auth {
      class org.factcast.server.grpc.auth.AccessRules {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace auth {
      class org.factcast.server.grpc.auth.FactCastAccessConfiguration {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace auth {
      class org.factcast.server.grpc.auth.FactCastAccount {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace auth {
      class org.factcast.server.grpc.auth.FactCastAuthority {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace auth {
      class org.factcast.server.grpc.auth.FactCastRole {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace auth {
      class org.factcast.server.grpc.auth.FactCastSecret {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace auth {
      class org.factcast.server.grpc.auth.FactCastUser {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace codec {
      class org.factcast.server.grpc.codec.Lz4GrpcServerCodec {
      }
    }
  }
  

  namespace org.factcast.server.grpc {
    namespace codec {
      class org.factcast.server.grpc.codec.SnappyGrpcServerCodec {
      }
    }
  }
  

  org.factcast.server.grpc.BlockingStreamObserver .up.|> io.grpc.stub.StreamObserver
  org.factcast.server.grpc.FactStoreGrpcService -up-|> org.factcast.grpc.api.gen.RemoteFactStoreGrpc.RemoteFactStoreImplBase
  org.factcast.server.grpc.FactStoreGrpcService o-- org.factcast.grpc.api.CompressionCodecs : codecs
  org.factcast.server.grpc.FactStoreGrpcService o-- org.factcast.grpc.api.conv.ProtoConverter : converter
  org.factcast.server.grpc.FactStoreGrpcService o-- org.factcast.server.grpc.GrpcLimitProperties : grpcLimitProperties
  org.factcast.server.grpc.FactStoreGrpcService o-- org.factcast.core.store.FactStore : store
  org.factcast.server.grpc.GrpcCompressionInterceptor .up.|> io.grpc.ServerInterceptor
  org.factcast.server.grpc.GrpcCompressionInterceptor o-- org.factcast.grpc.api.CompressionCodecs : codecs
  org.factcast.server.grpc.GrpcExceptionInterceptor .up.|> io.grpc.ServerInterceptor
  org.factcast.server.grpc.GrpcObserverAdapter .up.|> org.factcast.core.subscription.observer.FactObserver
  org.factcast.server.grpc.GrpcObserverAdapter o-- org.factcast.grpc.api.conv.ProtoConverter : converter
  org.factcast.server.grpc.auth.FactCastRole o-- org.factcast.server.grpc.auth.AccessRules : read
  org.factcast.server.grpc.auth.FactCastRole o-- org.factcast.server.grpc.auth.AccessRules : write
  org.factcast.server.grpc.auth.FactCastUser .up.|> org.springframework.security.core.CredentialsContainer
  org.factcast.server.grpc.auth.FactCastUser .up.|> org.springframework.security.core.userdetails.UserDetails
  org.factcast.server.grpc.auth.FactCastUser o-- org.factcast.server.grpc.auth.FactCastAccount : account
  org.factcast.server.grpc.codec.Lz4GrpcServerCodec .up.|> io.grpc.Codec
  org.factcast.server.grpc.codec.SnappyGrpcServerCodec .up.|> io.grpc.Codec


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
