baseURL = "https://docs.factcast.org/"
languageCode = "en-us"
title = "FactCast"
theme = "hugo-theme-docdock-master"
themesdir = "."

[params]
editURL ="https://github.com/uweschaefer/factcast/edit/master/factcast-site/documentation/content/"
noHomeIcon = true
noSearch = true
themeStyle = "original"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "Github repo <i class='fa fa-github'></i>"
identifier = "github"
url = "https://github.com/uweschaefer/factcast/"
weight = 1


[[menu.shortcuts]]

name = "Changelog"
identifier = "changelog"
url = "/changelog"
weight = 2

[[menu.shortcuts]]

name = "Migration"
identifier = "migration"
url = "/migration"
weight = 3


[[menu.shortcuts]]

name = "Contribution"
identifier = "thanks"
url = "/thanks"
weight = 100

[[menu.shortcuts]]

name = "Legal / Impressum"
identifier = "legal"
url = "/imprint"
weight = 999

