@startuml

interface Projection
interface SnapshotProjection
abstract class Aggregate #gold


abstract class  ManagedProjection
abstract class LocalManagedProjection

interface  SubscribedProjection
abstract class LocalSubscribedProjection

Projection <|-- SnapshotProjection
SnapshotProjection <|-- Aggregate


Projection <|-- ManagedProjection
ManagedProjection <|-- LocalManagedProjection

Projection <|-- SubscribedProjection
SubscribedProjection  <|-- LocalSubscribedProjection

@enduml
