@startuml

title __TRANSFORMATION's Class Diagram__\n

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl {
            + FactTransformerServiceImpl()
            + transformIfNecessary()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl {
            + FactTransformersFactoryImpl()
            + createFor()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.FactTransformersImpl {
            + FactTransformersImpl()
            + transformIfNecessary()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.SingleTransformation {
            - fromVersion : int
            - toVersion : int
            - transformationCode : Optional<String>
            + SingleTransformation()
            {static} + empty()
            + equals()
            + fromVersion()
            + hashCode()
            + key()
            {static} + of()
            {static} + of()
            + toString()
            + toVersion()
            + transformationCode()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        interface org.factcast.store.pgsql.registry.transformation.Transformation {
            {abstract} + fromVersion()
            {abstract} + key()
            {abstract} + toVersion()
            {abstract} + transformationCode()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationCacheCompactor {
            - days : int
            {static} - log : Logger
            + TransformationCacheCompactor()
            + compact()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationConfiguration {
            + factTransformerService()
            + factTransformersFactory()
            + transformationCache()
            + transformationCacheCompactor()
            + transformationChains()
            + transformationStore()
            + transformer()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationConflictException {
            {static} - serialVersionUID : long
            + TransformationConflictException()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationKey {
            - ns : String
            - type : String
            + equals()
            + hashCode()
            + ns()
            {static} + of()
            + toString()
            + type()
            {static} ~ from()
            - TransformationKey()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationSource {
            - from : Integer
            - hash : String
            - id : String
            - ns : String
            - to : Integer
            - type : String
            + TransformationSource()
            + TransformationSource()
            + equals()
            + from()
            + from()
            + hash()
            + hash()
            + hashCode()
            + id()
            + id()
            + isSynthetic()
            + ns()
            + ns()
            + to()
            + to()
            + toKey()
            + toString()
            + type()
            + type()
            + withFrom()
            + withHash()
            + withId()
            + withNs()
            + withTo()
            + withType()
            # canEqual()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        interface org.factcast.store.pgsql.registry.transformation.TransformationStore {
            {abstract} + contains()
            {abstract} + get()
            {abstract} + register()
            {abstract} + store()
            {abstract} + unregister()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        interface org.factcast.store.pgsql.registry.transformation.TransformationStoreListener {
            {abstract} + notifyFor()
        }
      }
    }
  }
  

  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl .up.|> org.factcast.core.subscription.FactTransformerService
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.transformation.cache.TransformationCache : cache
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.transformation.chains.TransformationChains : chains
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.transformation.chains.Transformer : trans
  org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl .up.|> org.factcast.core.subscription.FactTransformersFactory
  org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl o-- org.factcast.core.subscription.FactTransformerService : trans
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl .up.|> org.factcast.core.subscription.FactTransformers
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl o-- org.factcast.store.pgsql.internal.RequestedVersions : requested
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl o-- org.factcast.core.subscription.FactTransformerService : trans
  org.factcast.store.pgsql.registry.transformation.SingleTransformation .up.|> org.factcast.store.pgsql.registry.transformation.Transformation
  org.factcast.store.pgsql.registry.transformation.SingleTransformation o-- org.factcast.store.pgsql.registry.transformation.TransformationKey : key
  org.factcast.store.pgsql.registry.transformation.TransformationCacheCompactor o-- org.factcast.store.pgsql.registry.transformation.cache.TransformationCache : cache


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
