#!/bin/bash

set -e

PREFIX="> pre-commit [$(basename $0)]\t\t"
echo -e "$PREFIX checking using spotless"
mvn -q spotless:check || ( echo -e "$PREFIX Please format your java files according to the format definition in src/eclipse" && echo -e "$PREFIX You can do that by typing 'mvn spotless:apply' if your IDE does not help with that." && exit 1)
