spring.grpc.client.channel.factstore.keepalive.time=310
spring.grpc.client.channel.factstore.keepalive.without-calls=true
spring.grpc.client.channel.factstore.target=static://localhost:9443
spring.grpc.client.channel.factstore.ssl.bundle=examplebundle
spring.ssl.bundle.pem.examplebundle.truststore.certificate=file:///${project.basedir}/../../src/etc/certificates/localhost.crt

