@startuml

title __CHAINS's Class Diagram__\n

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.MissingTransformationInformation {
              {static} - serialVersionUID : long
              + MissingTransformationInformation()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.NashornTransformer {
              {static} - ENGINE_CACHE_CAPACITY : int
              {static} - scriptEngineManager : ScriptEngineManager
              {static} - warmEngines : LRUMap<String, Invocable>
              + transform()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationCacheKey {
              - fromVersion : int
              - toVersion : int
              + TransformationCacheKey()
              + equals()
              + fromVersion()
              + hashCode()
              + key()
              + toString()
              + toVersion()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationChain {
              - fromVersion : int
              - id : String
              - toVersion : int
              - transformationCode : Optional<String>
              + TransformationChain()
              + equals()
              + fromVersion()
              + hashCode()
              + id()
              + key()
              {static} + of()
              + toString()
              + toVersion()
              + transformationCode()
              {static} - createCompositeJS()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationChains {
              {static} - BASE_COST : double
              - cache : Map<TransformationKey, Map<VersionPath, TransformationChain>>
              + TransformationChains()
              + get()
              + notifyFor()
              - build()
              {static} - map()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationChains.Edge {
              - fromVersion : int
              - toVersion : int
              + equals()
              {static} + from()
              + fromVersion()
              + hashCode()
              {static} + of()
              + toString()
              + toVersion()
              + transformation()
              - Edge()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationChains.VersionPath {
              - fromVersion : int
              - toVersion : int
              + VersionPath()
              + equals()
              + fromVersion()
              + hashCode()
              + toString()
              + toVersion()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          interface org.factcast.store.pgsql.registry.transformation.chains.Transformer {
              {abstract} + transform()
          }
        }
      }
    }
  }
  

  org.factcast.store.pgsql.registry.transformation.chains.NashornTransformer .up.|> org.factcast.store.pgsql.registry.transformation.chains.Transformer
  org.factcast.store.pgsql.registry.transformation.chains.TransformationCacheKey o-- org.factcast.store.pgsql.registry.transformation.TransformationKey : key
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChain .up.|> org.factcast.store.pgsql.registry.transformation.Transformation
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChain o-- org.factcast.store.pgsql.registry.transformation.TransformationKey : key
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains .up.|> org.factcast.store.pgsql.registry.transformation.TransformationStoreListener
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains o-- org.factcast.store.pgsql.registry.SchemaRegistry : registry
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains +-down- org.factcast.store.pgsql.registry.transformation.chains.TransformationChains.Edge
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains +-down- org.factcast.store.pgsql.registry.transformation.chains.TransformationChains.VersionPath
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains.Edge o-- org.factcast.store.pgsql.registry.transformation.Transformation : transformation


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
