@startuml

title __METRICS's Class Diagram__\n

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        enum MetricEvent {
          FACT_VALIDATION_FAILED
          MISSING_TRANSFORMATION_INFO
          REGISTRY_FILE_FETCH_FAILED
          SCHEMA_CONFLICT
          SCHEMA_MISSING
          SCHEMA_REGISTRY_UNAVAILABLE
          TRANSFORMATION_CACHE_HIT
          TRANSFORMATION_CACHE_MISS
          TRANSFORMATION_CONFLICT
          TRANSFORMATION_FAILED
          event
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        interface org.factcast.store.pgsql.registry.metrics.RegistryMetrics {
            {static} + TAG_IDENTITY_KEY : String
            {static} + TAG_STATUS_CODE_KEY : String
            {abstract} + count()
            {abstract} + count()
            {abstract} + timed()
            {abstract} + timed()
            {abstract} + timed()
            {abstract} + timed()
            {abstract} + timed()
            {abstract} + timed()
            {abstract} + timed()
            {abstract} + timed()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        class org.factcast.store.pgsql.registry.metrics.RegistryMetricsImpl {
            {static} + METRIC_NAME_COUNTS : String
            {static} + METRIC_NAME_TIMINGS : String
            {static} + TAG_NAME_KEY : String
            - meterRegistry : MeterRegistry
            + RegistryMetricsImpl()
            + count()
            + count()
            + timed()
            + timed()
            + timed()
            + timed()
            + timed()
            + timed()
            + timed()
            + timed()
            - counter()
            - timer()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        interface org.factcast.store.pgsql.registry.metrics.RunnableWithException {
            {abstract} + run()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        interface org.factcast.store.pgsql.registry.metrics.SupplierWithException {
            {abstract} + get()
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        enum TimedOperation {
          COMPACT_TRANSFORMATION_CACHE
          FETCH_REGISTRY_FILE
          REFRESH_REGISTRY
          TRANSFORMATION
          op
        }
      }
    }
  }
  

  org.factcast.store.pgsql.registry.metrics.RegistryMetricsImpl .up.|> org.factcast.store.pgsql.registry.metrics.RegistryMetrics


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
