@startuml

title __FACTCAST-STORE-PGSQL's Class Diagram__\n

  namespace org.factcast.store.pgsql {
    enum CatchupStrategy {
    }
  }
  

  namespace org.factcast.store.pgsql {
    class org.factcast.store.pgsql.PgConfigurationProperties {
    }
  }
  

  namespace org.factcast.store.pgsql {
    class org.factcast.store.pgsql.PgFactStoreConfiguration {
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.CondensedQueryExecutor {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgConstants {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgFact {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgFactStore {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgFactStoreInternalConfiguration {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgFactStream {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgMetrics {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgPostQueryMatcher {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgSubscriptionFactory {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgSynchronizedQuery {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.PgTokenStore {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      class org.factcast.store.pgsql.internal.RequestedVersions {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        class org.factcast.store.pgsql.internal.catchup.PgCatchUpFetchPage {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        class org.factcast.store.pgsql.internal.catchup.PgCatchUpPrepare {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        interface org.factcast.store.pgsql.internal.catchup.PgCatchup {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        interface org.factcast.store.pgsql.internal.catchup.PgCatchupFactory {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        namespace paged {
          class org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace catchup {
        namespace paged {
          class org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace listen {
        class org.factcast.store.pgsql.internal.listen.PgConnectionSupplier {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace listen {
        class org.factcast.store.pgsql.internal.listen.PgConnectionTester {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace listen {
        class org.factcast.store.pgsql.internal.listen.PgListener {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace lock {
        enum AdvisoryLocks {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace lock {
        class org.factcast.store.pgsql.internal.lock.AdvisoryWriteLock {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace lock {
        interface org.factcast.store.pgsql.internal.lock.FactTableWriteLock {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace query {
        class org.factcast.store.pgsql.internal.query.PgFactIdToSerialMapper {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace query {
        class org.factcast.store.pgsql.internal.query.PgLatestSerialFetcher {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace query {
        class org.factcast.store.pgsql.internal.query.PgQueryBuilder {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace rowmapper {
        class org.factcast.store.pgsql.internal.rowmapper.PgFactExtractor {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace snapcache {
        class org.factcast.store.pgsql.internal.snapcache.PgSnapshotData {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace snapcache {
        class org.factcast.store.pgsql.internal.snapcache.SnapshotCache {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace snapcache {
        class org.factcast.store.pgsql.internal.snapcache.SnapshotCacheCompactor {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace internal {
      namespace snapcache {
        class org.factcast.store.pgsql.internal.snapcache.SnapshotCacheConfiguration {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      abstract class org.factcast.store.pgsql.registry.AbstractSchemaRegistry {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      interface org.factcast.store.pgsql.registry.IndexFetcher {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      class org.factcast.store.pgsql.registry.NOPSchemaRegistry {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      class org.factcast.store.pgsql.registry.RegistryFileFetchException {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      interface org.factcast.store.pgsql.registry.RegistryFileFetcher {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      class org.factcast.store.pgsql.registry.RegistryIndex {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      class org.factcast.store.pgsql.registry.ScheduledRegistryRefresher {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      interface org.factcast.store.pgsql.registry.SchemaRegistry {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      class org.factcast.store.pgsql.registry.SchemaRegistryConfiguration {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      class org.factcast.store.pgsql.registry.SchemaRegistryUnavailableException {
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace classpath {
        class org.factcast.store.pgsql.registry.classpath.ClasspathIndexFetcher {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace classpath {
        class org.factcast.store.pgsql.registry.classpath.ClasspathRegistryFileFetcher {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace classpath {
        class org.factcast.store.pgsql.registry.classpath.ClasspathSchemaRegistry {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace http {
        class org.factcast.store.pgsql.registry.http.HttpIndexFetcher {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace http {
        class org.factcast.store.pgsql.registry.http.HttpRegistryFileFetcher {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace http {
        class org.factcast.store.pgsql.registry.http.HttpSchemaRegistry {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace http {
        class org.factcast.store.pgsql.registry.http.ValidationConstants {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        enum MetricEvent {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        interface org.factcast.store.pgsql.registry.metrics.RegistryMetrics {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        class org.factcast.store.pgsql.registry.metrics.RegistryMetricsImpl {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        interface org.factcast.store.pgsql.registry.metrics.RunnableWithException {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        interface org.factcast.store.pgsql.registry.metrics.SupplierWithException {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace metrics {
        enum TimedOperation {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.FactTransformersImpl {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.SingleTransformation {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        interface org.factcast.store.pgsql.registry.transformation.Transformation {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationCacheCompactor {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationConfiguration {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationConflictException {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationKey {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        class org.factcast.store.pgsql.registry.transformation.TransformationSource {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        interface org.factcast.store.pgsql.registry.transformation.TransformationStore {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        interface org.factcast.store.pgsql.registry.transformation.TransformationStoreListener {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace cache {
          class org.factcast.store.pgsql.registry.transformation.cache.CacheKey {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace cache {
          class org.factcast.store.pgsql.registry.transformation.cache.InMemTransformationCache {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace cache {
          class org.factcast.store.pgsql.registry.transformation.cache.PgTransformationCache {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace cache {
          interface org.factcast.store.pgsql.registry.transformation.cache.TransformationCache {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.MissingTransformationInformation {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.NashornTransformer {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationCacheKey {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationChain {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          class org.factcast.store.pgsql.registry.transformation.chains.TransformationChains {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace chains {
          interface org.factcast.store.pgsql.registry.transformation.chains.Transformer {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace store {
          abstract class org.factcast.store.pgsql.registry.transformation.store.AbstractTransformationStore {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace store {
          class org.factcast.store.pgsql.registry.transformation.store.InMemTransformationStoreImpl {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace transformation {
        namespace store {
          class org.factcast.store.pgsql.registry.transformation.store.PgTransformationStoreImpl {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        class org.factcast.store.pgsql.registry.validation.FactValidationAspect {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        class org.factcast.store.pgsql.registry.validation.FactValidationError {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        class org.factcast.store.pgsql.registry.validation.FactValidator {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        class org.factcast.store.pgsql.registry.validation.FactValidatorConfiguration {
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          class org.factcast.store.pgsql.registry.validation.schema.SchemaConflictException {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          class org.factcast.store.pgsql.registry.validation.schema.SchemaKey {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          class org.factcast.store.pgsql.registry.validation.schema.SchemaSource {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          interface org.factcast.store.pgsql.registry.validation.schema.SchemaStore {
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          namespace store {
            class org.factcast.store.pgsql.registry.validation.schema.store.InMemSchemaStoreImpl {
            }
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          namespace store {
            class org.factcast.store.pgsql.registry.validation.schema.store.PgSchemaStoreImpl {
            }
          }
        }
      }
    }
  }
  

  org.factcast.store.pgsql.PgConfigurationProperties .up.|> org.springframework.context.ApplicationListener
  org.factcast.store.pgsql.PgConfigurationProperties o-- org.factcast.store.pgsql.CatchupStrategy : catchupStrategy
  org.factcast.store.pgsql.internal.CondensedQueryExecutor o-- org.factcast.store.pgsql.internal.PgSynchronizedQuery : target
  org.factcast.store.pgsql.internal.PgFact .up.|> org.factcast.core.Fact
  org.factcast.store.pgsql.internal.PgFact o-- org.factcast.core.FactHeader : header
  org.factcast.store.pgsql.internal.PgFactStore -up-|> org.factcast.core.store.AbstractFactStore
  org.factcast.store.pgsql.internal.PgFactStore o-- org.factcast.core.subscription.FactTransformerService : factTransformerService
  org.factcast.store.pgsql.internal.PgFactStore o-- org.factcast.store.pgsql.internal.lock.FactTableWriteLock : lock
  org.factcast.store.pgsql.internal.PgFactStore o-- org.factcast.store.pgsql.internal.PgMetrics : metrics
  org.factcast.store.pgsql.internal.PgFactStore o-- org.factcast.store.pgsql.internal.snapcache.SnapshotCache : snapCache
  org.factcast.store.pgsql.internal.PgFactStore o-- org.factcast.store.pgsql.internal.PgSubscriptionFactory : subscriptionFactory
  org.factcast.store.pgsql.internal.PgFactStream o-- org.factcast.store.pgsql.internal.CondensedQueryExecutor : condensedExecutor
  org.factcast.store.pgsql.internal.PgFactStream o-- org.factcast.store.pgsql.internal.query.PgLatestSerialFetcher : fetcher
  org.factcast.store.pgsql.internal.PgFactStream o-- org.factcast.store.pgsql.internal.query.PgFactIdToSerialMapper : idToSerMapper
  org.factcast.store.pgsql.internal.PgFactStream o-- org.factcast.store.pgsql.internal.catchup.PgCatchupFactory : pgCatchupFactory
  org.factcast.store.pgsql.internal.PgFactStream o-- org.factcast.store.pgsql.internal.PgPostQueryMatcher : postQueryMatcher
  org.factcast.store.pgsql.internal.PgFactStream o-- org.factcast.core.subscription.SubscriptionRequestTO : request
  org.factcast.store.pgsql.internal.PgFactStream o-- org.factcast.core.subscription.SubscriptionImpl : subscription
  org.factcast.store.pgsql.internal.PgPostQueryMatcher .up.|> java.util.function.Predicate
  org.factcast.store.pgsql.internal.PgSubscriptionFactory o-- org.factcast.store.pgsql.internal.catchup.PgCatchupFactory : catchupFactory
  org.factcast.store.pgsql.internal.PgSubscriptionFactory o-- org.factcast.store.pgsql.internal.query.PgLatestSerialFetcher : fetcher
  org.factcast.store.pgsql.internal.PgSubscriptionFactory o-- org.factcast.store.pgsql.internal.query.PgFactIdToSerialMapper : idToSerialMapper
  org.factcast.store.pgsql.internal.PgSubscriptionFactory o-- org.factcast.core.subscription.FactTransformersFactory : transformersFactory
  org.factcast.store.pgsql.internal.PgSynchronizedQuery o-- org.factcast.store.pgsql.internal.query.PgLatestSerialFetcher : latestFetcher
  org.factcast.store.pgsql.internal.PgTokenStore .up.|> org.factcast.core.store.TokenStore
  org.factcast.store.pgsql.internal.catchup.PgCatchUpFetchPage o-- org.factcast.core.subscription.SubscriptionRequestTO : req
  org.factcast.store.pgsql.internal.catchup.PgCatchUpPrepare o-- org.factcast.core.subscription.SubscriptionRequestTO : req
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory .up.|> org.factcast.store.pgsql.internal.catchup.PgCatchupFactory
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory o-- org.factcast.store.pgsql.PgConfigurationProperties : props
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchUpFactory o-- org.factcast.store.pgsql.internal.query.PgFactIdToSerialMapper : serMapper
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup .up.|> org.factcast.store.pgsql.internal.catchup.PgCatchup
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.store.pgsql.internal.PgPostQueryMatcher : postQueryMatcher
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.store.pgsql.PgConfigurationProperties : props
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.core.subscription.SubscriptionRequestTO : request
  org.factcast.store.pgsql.internal.catchup.paged.PgPagedCatchup o-- org.factcast.core.subscription.SubscriptionImpl : subscription
  org.factcast.store.pgsql.internal.listen.PgConnectionTester .up.|> java.util.function.Predicate
  org.factcast.store.pgsql.internal.listen.PgListener .up.|> org.springframework.beans.factory.DisposableBean
  org.factcast.store.pgsql.internal.listen.PgListener .up.|> org.springframework.beans.factory.InitializingBean
  org.factcast.store.pgsql.internal.listen.PgListener o-- org.factcast.store.pgsql.internal.listen.PgConnectionSupplier : pgConnectionSupplier
  org.factcast.store.pgsql.internal.listen.PgListener o-- org.factcast.store.pgsql.internal.PgMetrics : pgMetrics
  org.factcast.store.pgsql.internal.listen.PgListener o-- org.factcast.store.pgsql.PgConfigurationProperties : props
  org.factcast.store.pgsql.internal.lock.AdvisoryWriteLock .up.|> org.factcast.store.pgsql.internal.lock.FactTableWriteLock
  org.factcast.store.pgsql.internal.query.PgQueryBuilder o-- org.factcast.core.subscription.SubscriptionRequestTO : req
  org.factcast.store.pgsql.internal.rowmapper.PgFactExtractor .up.|> org.springframework.jdbc.core.RowMapper
  org.factcast.store.pgsql.internal.snapcache.SnapshotCacheCompactor o-- org.factcast.store.pgsql.internal.snapcache.SnapshotCache : cache
  org.factcast.store.pgsql.internal.snapcache.SnapshotCacheCompactor o-- org.factcast.store.pgsql.internal.PgMetrics : pgMetrics
  org.factcast.store.pgsql.registry.AbstractSchemaRegistry .up.|> org.factcast.store.pgsql.registry.SchemaRegistry
  org.factcast.store.pgsql.registry.AbstractSchemaRegistry o-- org.factcast.store.pgsql.registry.IndexFetcher : indexFetcher
  org.factcast.store.pgsql.registry.AbstractSchemaRegistry o-- org.factcast.store.pgsql.registry.RegistryFileFetcher : registryFileFetcher
  org.factcast.store.pgsql.registry.AbstractSchemaRegistry o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.AbstractSchemaRegistry o-- org.factcast.store.pgsql.registry.validation.schema.SchemaStore : schemaStore
  org.factcast.store.pgsql.registry.AbstractSchemaRegistry o-- org.factcast.store.pgsql.registry.transformation.TransformationStore : transformationStore
  org.factcast.store.pgsql.registry.NOPSchemaRegistry .up.|> org.factcast.store.pgsql.registry.SchemaRegistry
  org.factcast.store.pgsql.registry.RegistryFileFetchException -up-|> java.io.IOException
  org.factcast.store.pgsql.registry.ScheduledRegistryRefresher o-- org.factcast.store.pgsql.registry.SchemaRegistry : registry
  org.factcast.store.pgsql.registry.classpath.ClasspathIndexFetcher .up.|> org.factcast.store.pgsql.registry.IndexFetcher
  org.factcast.store.pgsql.registry.classpath.ClasspathRegistryFileFetcher .up.|> org.factcast.store.pgsql.registry.RegistryFileFetcher
  org.factcast.store.pgsql.registry.classpath.ClasspathSchemaRegistry -up-|> org.factcast.store.pgsql.registry.AbstractSchemaRegistry
  org.factcast.store.pgsql.registry.http.HttpIndexFetcher .up.|> org.factcast.store.pgsql.registry.IndexFetcher
  org.factcast.store.pgsql.registry.http.HttpIndexFetcher o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.http.HttpRegistryFileFetcher .up.|> org.factcast.store.pgsql.registry.RegistryFileFetcher
  org.factcast.store.pgsql.registry.http.HttpRegistryFileFetcher o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.http.HttpSchemaRegistry -up-|> org.factcast.store.pgsql.registry.AbstractSchemaRegistry
  org.factcast.store.pgsql.registry.metrics.RegistryMetricsImpl .up.|> org.factcast.store.pgsql.registry.metrics.RegistryMetrics
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl .up.|> org.factcast.core.subscription.FactTransformerService
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.transformation.cache.TransformationCache : cache
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.transformation.chains.TransformationChains : chains
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.FactTransformerServiceImpl o-- org.factcast.store.pgsql.registry.transformation.chains.Transformer : trans
  org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl .up.|> org.factcast.core.subscription.FactTransformersFactory
  org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.FactTransformersFactoryImpl o-- org.factcast.core.subscription.FactTransformerService : trans
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl .up.|> org.factcast.core.subscription.FactTransformers
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl o-- org.factcast.store.pgsql.internal.RequestedVersions : requested
  org.factcast.store.pgsql.registry.transformation.FactTransformersImpl o-- org.factcast.core.subscription.FactTransformerService : trans
  org.factcast.store.pgsql.registry.transformation.SingleTransformation .up.|> org.factcast.store.pgsql.registry.transformation.Transformation
  org.factcast.store.pgsql.registry.transformation.SingleTransformation o-- org.factcast.store.pgsql.registry.transformation.TransformationKey : key
  org.factcast.store.pgsql.registry.transformation.TransformationCacheCompactor o-- org.factcast.store.pgsql.registry.transformation.cache.TransformationCache : cache
  org.factcast.store.pgsql.registry.transformation.cache.InMemTransformationCache .up.|> org.factcast.store.pgsql.registry.transformation.cache.TransformationCache
  org.factcast.store.pgsql.registry.transformation.cache.InMemTransformationCache o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.cache.PgTransformationCache .up.|> org.factcast.store.pgsql.registry.transformation.cache.TransformationCache
  org.factcast.store.pgsql.registry.transformation.cache.PgTransformationCache o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.chains.NashornTransformer .up.|> org.factcast.store.pgsql.registry.transformation.chains.Transformer
  org.factcast.store.pgsql.registry.transformation.chains.TransformationCacheKey o-- org.factcast.store.pgsql.registry.transformation.TransformationKey : key
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChain .up.|> org.factcast.store.pgsql.registry.transformation.Transformation
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChain o-- org.factcast.store.pgsql.registry.transformation.TransformationKey : key
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains .up.|> org.factcast.store.pgsql.registry.transformation.TransformationStoreListener
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains o-- org.factcast.store.pgsql.registry.SchemaRegistry : registry
  org.factcast.store.pgsql.registry.transformation.chains.TransformationChains o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.store.AbstractTransformationStore .up.|> org.factcast.store.pgsql.registry.transformation.TransformationStore
  org.factcast.store.pgsql.registry.transformation.store.InMemTransformationStoreImpl -up-|> org.factcast.store.pgsql.registry.transformation.store.AbstractTransformationStore
  org.factcast.store.pgsql.registry.transformation.store.InMemTransformationStoreImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.transformation.store.PgTransformationStoreImpl -up-|> org.factcast.store.pgsql.registry.transformation.store.AbstractTransformationStore
  org.factcast.store.pgsql.registry.transformation.store.PgTransformationStoreImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.validation.FactValidationAspect o-- org.factcast.store.pgsql.registry.validation.FactValidator : validator
  org.factcast.store.pgsql.registry.validation.FactValidator o-- org.factcast.store.pgsql.PgConfigurationProperties : props
  org.factcast.store.pgsql.registry.validation.FactValidator o-- org.factcast.store.pgsql.registry.SchemaRegistry : registry
  org.factcast.store.pgsql.registry.validation.FactValidator o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.validation.schema.store.InMemSchemaStoreImpl .up.|> org.factcast.store.pgsql.registry.validation.schema.SchemaStore
  org.factcast.store.pgsql.registry.validation.schema.store.InMemSchemaStoreImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.validation.schema.store.PgSchemaStoreImpl .up.|> org.factcast.store.pgsql.registry.validation.schema.SchemaStore
  org.factcast.store.pgsql.registry.validation.schema.store.PgSchemaStoreImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
