@startuml

title __FACTCAST-HIGHLEVEL-CORE's Class Diagram__\n

  namespace org.factcast.highlevel {
    class org.factcast.highlevel.DefaultEventCast {
    }
  }
  

  namespace org.factcast.highlevel {
    interface org.factcast.highlevel.EventCast {
    }
  }
  

  namespace org.factcast.highlevel {
    interface org.factcast.highlevel.EventPojo {
    }
  }
  

  namespace org.factcast.highlevel {
    interface org.factcast.highlevel.Handler {
    }
  }
  

  namespace org.factcast.highlevel {
    interface org.factcast.highlevel.HandlerFor {
    }
  }
  

  namespace org.factcast.highlevel {
    namespace applier {
      class org.factcast.highlevel.applier.DefaultEventApplier {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace applier {
      class org.factcast.highlevel.applier.DefaultEventApplierFactory {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace applier {
      interface org.factcast.highlevel.applier.EventApplier {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace applier {
      interface org.factcast.highlevel.applier.EventApplierFactory {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace batch {
      class org.factcast.highlevel.batch.BatchAbortedException {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace batch {
      class org.factcast.highlevel.batch.DefaultPublishBatch {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace batch {
      interface org.factcast.highlevel.batch.PublishBatch {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      abstract class org.factcast.highlevel.projection.Aggregate {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      abstract class org.factcast.highlevel.projection.ExternallyManagedProjection {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      abstract class org.factcast.highlevel.projection.LocalManagedProjection {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.ManagedProjection {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.Projection {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.SnapshotProjection {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.StateAware {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace serializer {
      class org.factcast.highlevel.serializer.DefaultEventSerializer {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace serializer {
      class org.factcast.highlevel.serializer.DefaultSnapshotSerializer {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace serializer {
      interface org.factcast.highlevel.serializer.EventSerializer {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace serializer {
      interface org.factcast.highlevel.serializer.SnapshotSerializer {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace snapshot {
      class org.factcast.highlevel.snapshot.AggregateSnapshot {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace snapshot {
      interface org.factcast.highlevel.snapshot.AggregateSnapshotRepository {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace snapshot {
      class org.factcast.highlevel.snapshot.AggregateSnapshotRepositoryImpl {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace snapshot {
      class org.factcast.highlevel.snapshot.ProjectionSnapshot {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace snapshot {
      interface org.factcast.highlevel.snapshot.ProjectionSnapshotRepository {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace snapshot {
      class org.factcast.highlevel.snapshot.ProjectionSnapshotRepositoryImpl {
      }
    }
  }
  

  org.factcast.highlevel.DefaultEventCast .up.|> org.factcast.highlevel.EventCast
  org.factcast.highlevel.DefaultEventCast o-- org.factcast.highlevel.snapshot.AggregateSnapshotRepository : aggregateSnapshotRepository
  org.factcast.highlevel.DefaultEventCast o-- org.factcast.highlevel.applier.EventApplierFactory : ehFactory
  org.factcast.highlevel.DefaultEventCast o-- org.factcast.core.FactCast : fc
  org.factcast.highlevel.DefaultEventCast o-- org.factcast.highlevel.snapshot.ProjectionSnapshotRepository : projectionSnapshotRepository
  org.factcast.highlevel.DefaultEventCast o-- org.factcast.highlevel.serializer.EventSerializer : serializer
  org.factcast.highlevel.applier.DefaultEventApplier .up.|> org.factcast.highlevel.applier.EventApplier
  org.factcast.highlevel.applier.DefaultEventApplier o-- org.factcast.highlevel.projection.Projection : projection
  org.factcast.highlevel.applier.DefaultEventApplierFactory .up.|> org.factcast.highlevel.applier.EventApplierFactory
  org.factcast.highlevel.applier.DefaultEventApplierFactory o-- org.factcast.highlevel.serializer.EventSerializer : deser
  org.factcast.highlevel.batch.DefaultPublishBatch .up.|> org.factcast.highlevel.batch.PublishBatch
  org.factcast.highlevel.batch.DefaultPublishBatch o-- org.factcast.highlevel.batch.BatchAbortedException : abortedException
  org.factcast.highlevel.batch.DefaultPublishBatch o-- org.factcast.core.FactCast : fc
  org.factcast.highlevel.batch.DefaultPublishBatch o-- org.factcast.highlevel.serializer.EventSerializer : serializer
  org.factcast.highlevel.projection.Aggregate .up.|> org.factcast.highlevel.projection.SnapshotProjection
  org.factcast.highlevel.projection.ExternallyManagedProjection .up.|> org.factcast.highlevel.projection.ManagedProjection
  org.factcast.highlevel.projection.LocalManagedProjection .up.|> org.factcast.highlevel.projection.ManagedProjection
  org.factcast.highlevel.serializer.DefaultEventSerializer .up.|> org.factcast.highlevel.serializer.EventSerializer
  org.factcast.highlevel.serializer.DefaultSnapshotSerializer .up.|> org.factcast.highlevel.serializer.SnapshotSerializer
  org.factcast.highlevel.snapshot.AggregateSnapshotRepositoryImpl .up.|> org.factcast.highlevel.snapshot.AggregateSnapshotRepository
  org.factcast.highlevel.snapshot.AggregateSnapshotRepositoryImpl o-- org.factcast.core.snap.SnapshotRepository : snap
  org.factcast.highlevel.snapshot.ProjectionSnapshotRepositoryImpl .up.|> org.factcast.highlevel.snapshot.ProjectionSnapshotRepository
  org.factcast.highlevel.snapshot.ProjectionSnapshotRepositoryImpl o-- org.factcast.core.snap.SnapshotRepository : snap


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
