version: '2.0'
services:

  factcast:
    image: factcast/factcast:0.2.5-SNAPSHOT
    ports:
      - "9443:9443"
    environment:
      - SPRING_CONFIG_LOCATION=/config/
    volumes:
      - ./config:/config
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: fc
      POSTGRES_USER: fc
      POSTGRES_DB: fc
    ports:
      - "15432:5432"


      