= Prerequisites
:icons: font



== Postgres

In order to run the FactCast server, you have to provide a Postgres database at least in version 15.
The following example shows the configuration with one user.

----
spring.datasource.username="user" //that user has to be provided
spring.datasource.password="password"
----

The user has to be a superuser, as it will also install Postgres modules like https://www.postgresql.org/docs/15/uuid-ossp.html[uuid-ossp].

=== If You Don't Want to Provide a Superuser

If you don't want to provide a superuser, you have to consider the following points:

. The database user needs at least the permission to query the `pg_roles` view.
According to the https://www.postgresql.org/docs/15/view-pg-roles.html[documentation] it's publicly accessible, so that shouldn't be a problem.
. FactCast needs the Postgres module https://www.postgresql.org/docs/15/uuid-ossp.html[uuid-ossp].
You have to install that module manually.
The server will recognise the already installed module and it won't throw an error caused by missing privileges.
Log in to your Postgres console and execute the following command as superuser:
+
[source,sql]
----
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
----