@startuml

title __PROJECTION's Class Diagram__\n

  namespace org.factcast.highlevel {
    namespace projection {
      abstract class org.factcast.highlevel.projection.Aggregate {
          - id : UUID
          + id()
          # id()
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      abstract class org.factcast.highlevel.projection.ExternallyManagedProjection {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      abstract class org.factcast.highlevel.projection.LocalManagedProjection {
          - mutex : Object
          - state : UUID
          + state()
          + state()
          + withLock()
          + withLock()
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.ManagedProjection {
          + withLock()
          {abstract} + withLock()
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.Projection {
          + postprocess()
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.SnapshotProjection {
      }
    }
  }
  

  namespace org.factcast.highlevel {
    namespace projection {
      interface org.factcast.highlevel.projection.StateAware {
          {abstract} + state()
          {abstract} + state()
      }
    }
  }
  

  org.factcast.highlevel.projection.Aggregate .up.|> org.factcast.highlevel.projection.SnapshotProjection
  org.factcast.highlevel.projection.ExternallyManagedProjection .up.|> org.factcast.highlevel.projection.ManagedProjection
  org.factcast.highlevel.projection.LocalManagedProjection .up.|> org.factcast.highlevel.projection.ManagedProjection


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
