factcast.store.schema-registry-url=file:///config/example-registry
factcast.store.persistent-registry=false
factcast.store.integration-test-mode=true
factcast.store.allow-unvalidated-publish=true
logging.level.org.factcast=INFO
