@startuml

title __STORE's Class Diagram__\n

  namespace org.factcast.core {
    namespace store {
      abstract class org.factcast.core.store.AbstractFactStore {
          + AbstractFactStore()
          + invalidate()
          + publishIfUnchanged()
          + stateFor()
          {abstract} # getStateFor()
          # isStateUnchanged()
          - sameValue()
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      interface org.factcast.core.store.FactStore {
          {abstract} + clearSnapshot()
          {abstract} + currentTime()
          {abstract} + enumerateNamespaces()
          {abstract} + enumerateTypes()
          {abstract} + fetchById()
          {abstract} + fetchByIdAndVersion()
          {abstract} + getSnapshot()
          {abstract} + invalidate()
          {abstract} + publish()
          {abstract} + publishIfUnchanged()
          {abstract} + serialOf()
          {abstract} + setSnapshot()
          {abstract} + stateFor()
          {abstract} + subscribe()
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      class org.factcast.core.store.RetryableException {
          {static} - serialVersionUID : long
          + RetryableException()
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      class org.factcast.core.store.StateToken {
          - uuid : UUID
          + StateToken()
          + StateToken()
          + equals()
          + hashCode()
          + toString()
          + uuid()
      }
    }
  }
  

  namespace org.factcast.core {
    namespace store {
      interface org.factcast.core.store.TokenStore {
          {abstract} + create()
          {abstract} + getNs()
          {abstract} + getState()
          {abstract} + invalidate()
      }
    }
  }
  

  org.factcast.core.store.AbstractFactStore .up.|> org.factcast.core.store.FactStore
  org.factcast.core.store.AbstractFactStore o-- org.factcast.core.store.TokenStore : tokenStore


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
