@startuml

title __STORE's Class Diagram__\n

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          namespace store {
            class org.factcast.store.pgsql.registry.validation.schema.store.InMemSchemaStoreImpl {
                - id2hashMap : Map<String, String>
                - mutex : Object
                - schemaMap : Map<SchemaKey, String>
                + InMemSchemaStoreImpl()
                + contains()
                + get()
                + register()
            }
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          namespace store {
            class org.factcast.store.pgsql.registry.validation.schema.store.PgSchemaStoreImpl {
                - jdbcTemplate : JdbcTemplate
                + PgSchemaStoreImpl()
                + contains()
                + get()
                + register()
            }
          }
        }
      }
    }
  }
  

  org.factcast.store.pgsql.registry.validation.schema.store.InMemSchemaStoreImpl .up.|> org.factcast.store.pgsql.registry.validation.schema.SchemaStore
  org.factcast.store.pgsql.registry.validation.schema.store.InMemSchemaStoreImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics
  org.factcast.store.pgsql.registry.validation.schema.store.PgSchemaStoreImpl .up.|> org.factcast.store.pgsql.registry.validation.schema.SchemaStore
  org.factcast.store.pgsql.registry.validation.schema.store.PgSchemaStoreImpl o-- org.factcast.store.pgsql.registry.metrics.RegistryMetrics : registryMetrics


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
