/*
 * Copyright © 2017-2026 factcast.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.factcast.store.internal.query;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;

import java.sql.*;
import lombok.SneakyThrows;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

@ExtendWith(MockitoExtension.class)
class StatementTrackingConnectionTest {

  @Mock private Connection delegateConnection;

  @Mock private CurrentStatementHolder currentStatementHolder;

  @Mock private Statement statement;

  @Mock private PreparedStatement preparedStatement;

  @Mock private CallableStatement callableStatement;

  private StatementTrackingConnection underTest;

  @BeforeEach
  void setUp() {
    underTest = new StatementTrackingConnection(delegateConnection, currentStatementHolder);
  }

  @Nested
  class StatementCreation {

    @SneakyThrows
    @Test
    void createStatementSimple() {
      when(delegateConnection.createStatement()).thenReturn(statement);

      Statement s = underTest.createStatement();

      assertThat(s).isNotNull();
      verify(delegateConnection).createStatement();
      verify(currentStatementHolder).register(statement);
    }

    @SneakyThrows
    @Test
    void createStatementWithResultSetTypeAndConcurrency() {
      when(delegateConnection.createStatement(
              ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY))
          .thenReturn(statement);

      Statement s =
          underTest.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);

      assertThat(s).isNotNull();
      verify(delegateConnection)
          .createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
      verify(currentStatementHolder).register(statement);
    }

    @SneakyThrows
    @Test
    void createStatementWithHoldability() {
      when(delegateConnection.createStatement(
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT))
          .thenReturn(statement);

      Statement s =
          underTest.createStatement(
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT);

      assertThat(s).isNotNull();
      verify(delegateConnection)
          .createStatement(
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT);
      verify(currentStatementHolder).register(statement);
    }
  }

  @Nested
  class PreparedStatementCreation {

    @SneakyThrows
    @Test
    void prepareStatementSql() {
      String sql = "SELECT 1";
      when(delegateConnection.prepareStatement(sql)).thenReturn(preparedStatement);

      PreparedStatement ps = underTest.prepareStatement(sql);

      assertThat(ps).isNotNull();
      verify(delegateConnection).prepareStatement(sql);
      verify(currentStatementHolder).register(preparedStatement);
    }

    @SneakyThrows
    @Test
    void prepareStatementWithColumnIndexes() {
      String sql = "INSERT INTO test VALUES (?)";
      int[] columnIndexes = {1};
      when(delegateConnection.prepareStatement(sql, columnIndexes)).thenReturn(preparedStatement);

      PreparedStatement ps = underTest.prepareStatement(sql, columnIndexes);

      assertThat(ps).isNotNull();
      verify(delegateConnection).prepareStatement(sql, columnIndexes);
      verify(currentStatementHolder).register(preparedStatement);
    }

    @SneakyThrows
    @Test
    void prepareStatementWithColumnNames() {
      String sql = "INSERT INTO test VALUES (?)";
      String[] columnNames = {"id"};
      when(delegateConnection.prepareStatement(sql, columnNames)).thenReturn(preparedStatement);

      PreparedStatement ps = underTest.prepareStatement(sql, columnNames);

      assertThat(ps).isNotNull();
      verify(delegateConnection).prepareStatement(sql, columnNames);
      verify(currentStatementHolder).register(preparedStatement);
    }

    @SneakyThrows
    @Test
    void prepareStatementWithAutoGeneratedKeys() {
      String sql = "INSERT INTO test VALUES (?)";
      when(delegateConnection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS))
          .thenReturn(preparedStatement);

      PreparedStatement ps = underTest.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

      assertThat(ps).isNotNull();
      verify(delegateConnection).prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
      verify(currentStatementHolder).register(preparedStatement);
    }

    @SneakyThrows
    @Test
    void prepareStatementWithResultSetTypeAndConcurrency() {
      String sql = "SELECT 1";
      when(delegateConnection.prepareStatement(
              sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY))
          .thenReturn(preparedStatement);

      PreparedStatement ps =
          underTest.prepareStatement(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);

      assertThat(ps).isNotNull();
      verify(delegateConnection)
          .prepareStatement(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
      verify(currentStatementHolder).register(preparedStatement);
    }

    @SneakyThrows
    @Test
    void prepareStatementWithHoldability() {
      String sql = "SELECT 1";
      when(delegateConnection.prepareStatement(
              sql,
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT))
          .thenReturn(preparedStatement);

      PreparedStatement ps =
          underTest.prepareStatement(
              sql,
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT);

      assertThat(ps).isNotNull();
      verify(delegateConnection)
          .prepareStatement(
              sql,
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT);
      verify(currentStatementHolder).register(preparedStatement);
    }
  }

  @Nested
  class CallableStatementCreation {

    @SneakyThrows
    @Test
    void prepareCallSql() {
      String sql = "{call foo()}";
      when(delegateConnection.prepareCall(sql)).thenReturn(callableStatement);

      CallableStatement cs = underTest.prepareCall(sql);

      assertThat(cs).isNotNull();
      verify(delegateConnection).prepareCall(sql);
      verify(currentStatementHolder).register(callableStatement);
    }

    @SneakyThrows
    @Test
    void prepareCallWithResultSetTypeAndConcurrency() {
      String sql = "{call foo()}";
      when(delegateConnection.prepareCall(
              sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY))
          .thenReturn(callableStatement);

      CallableStatement cs =
          underTest.prepareCall(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);

      assertThat(cs).isNotNull();
      verify(delegateConnection)
          .prepareCall(sql, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
      verify(currentStatementHolder).register(callableStatement);
    }

    @SneakyThrows
    @Test
    void prepareCallWithHoldability() {
      String sql = "{call foo()}";
      when(delegateConnection.prepareCall(
              sql,
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT))
          .thenReturn(callableStatement);

      CallableStatement cs =
          underTest.prepareCall(
              sql,
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT);

      assertThat(cs).isNotNull();
      verify(delegateConnection)
          .prepareCall(
              sql,
              ResultSet.TYPE_FORWARD_ONLY,
              ResultSet.CONCUR_READ_ONLY,
              ResultSet.HOLD_CURSORS_OVER_COMMIT);
      verify(currentStatementHolder).register(callableStatement);
    }
  }

  @Nested
  class ContextStatementClosing {

    @SneakyThrows
    @Test
    void statementCloseUnregisters() {
      when(delegateConnection.createStatement()).thenReturn(statement);
      Statement s = underTest.createStatement();

      s.close();

      verify(statement).close();
      verify(currentStatementHolder).unregister(statement);
    }

    @SneakyThrows
    @Test
    void statementCloseOnCompletionUnregisters() {
      when(delegateConnection.createStatement()).thenReturn(statement);
      Statement s = underTest.createStatement();

      s.closeOnCompletion();

      verify(statement).closeOnCompletion();
      verify(currentStatementHolder).unregister(statement);
    }

    @SneakyThrows
    @Test
    void statementCloseThrowsExceptionStillUnregisters() {
      when(delegateConnection.createStatement()).thenReturn(statement);
      doThrow(new SQLException("close error")).when(statement).close();
      Statement s = underTest.createStatement();

      try {
        s.close();
      } catch (SQLException e) {
        assertThat(e.getMessage()).isEqualTo("close error");
      }

      verify(statement).close();
      verify(currentStatementHolder).unregister(statement);
    }

    @SneakyThrows
    @Test
    void preparedStatementCloseUnregisters() {
      when(delegateConnection.prepareStatement("SELECT 1")).thenReturn(preparedStatement);
      PreparedStatement ps = underTest.prepareStatement("SELECT 1");

      ps.close();

      verify(preparedStatement).close();
      verify(currentStatementHolder).unregister(preparedStatement);
    }

    @SneakyThrows
    @Test
    void callableStatementCloseUnregisters() {
      when(delegateConnection.prepareCall("{call foo()}")).thenReturn(callableStatement);
      CallableStatement cs = underTest.prepareCall("{call foo()}");

      cs.close();

      verify(callableStatement).close();
      verify(currentStatementHolder).unregister(callableStatement);
    }
  }

  @Nested
  class ConnectionDelegation {

    @SneakyThrows
    @Test
    void delegatesCommit() {
      underTest.commit();
      verify(delegateConnection).commit();
    }

    @SneakyThrows
    @Test
    void delegatesRollback() {
      underTest.rollback();
      verify(delegateConnection).rollback();
    }
  }
}
