@startuml

title __SNAP's Class Diagram__\n

  namespace org.factcast.core {
    namespace snap {
      class org.factcast.core.snap.FactCastSnapshotRepository {
          + FactCastSnapshotRepository()
          + clearSnapshot()
          + getSnapshot()
          + setSnapshot()
      }
    }
  }
  

  namespace org.factcast.core {
    namespace snap {
      class org.factcast.core.snap.Snapshot {
          - bytes : byte[]
          - lastFact : UUID
          + Snapshot()
          + bytes()
          + equals()
          + hashCode()
          + id()
          + lastFact()
          + toString()
      }
    }
  }
  

  namespace org.factcast.core {
    namespace snap {
      class org.factcast.core.snap.SnapshotId {
          - key : String
          - uuid : UUID
          + SnapshotId()
          + equals()
          + hashCode()
          + key()
          + toString()
          + uuid()
      }
    }
  }
  

  namespace org.factcast.core {
    namespace snap {
      interface org.factcast.core.snap.SnapshotRepository {
          {abstract} + clearSnapshot()
          {abstract} + getSnapshot()
          {abstract} + setSnapshot()
      }
    }
  }
  

  org.factcast.core.snap.FactCastSnapshotRepository .up.|> org.factcast.core.snap.SnapshotRepository
  org.factcast.core.snap.FactCastSnapshotRepository o-- org.factcast.core.store.FactStore : store
  org.factcast.core.snap.Snapshot o-- org.factcast.core.snap.SnapshotId : id


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
