/*
 * Copyright © 2017-2026 factcast.org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.factcast.store.internal.query;

import java.sql.*;
import lombok.*;
import lombok.experimental.Delegate;

/**
 * when creating a statement, it'll be registered to the currentStatementHolder and unregisters
 * itself on close.
 */
@RequiredArgsConstructor
class StatementTrackingConnection implements Connection {
  @Delegate final Connection delegate;
  final CurrentStatementHolder currentStatementHolder;

  @Override
  public Statement createStatement() throws SQLException {
    Statement statement = delegate.createStatement();
    currentStatementHolder.register(statement);
    return new ContextStatement(statement);
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency)
      throws SQLException {
    Statement statement = delegate.createStatement(resultSetType, resultSetConcurrency);
    currentStatementHolder.register(statement);
    return new ContextStatement(statement);
  }

  @Override
  public Statement createStatement(
      int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
    Statement statement =
        delegate.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
    currentStatementHolder.register(statement);
    return new ContextStatement(statement);
  }

  @Override
  public PreparedStatement prepareStatement(String sql) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql);
    currentStatementHolder.register(statement);
    return new ContextPreparedStatement(statement);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, columnIndexes);
    currentStatementHolder.register(statement);
    return new ContextPreparedStatement(statement);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, columnNames);
    currentStatementHolder.register(statement);
    return new ContextPreparedStatement(statement);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
    PreparedStatement statement = delegate.prepareStatement(sql, autoGeneratedKeys);
    currentStatementHolder.register(statement);
    return new ContextPreparedStatement(statement);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
      throws SQLException {
    PreparedStatement statement =
        delegate.prepareStatement(sql, resultSetType, resultSetConcurrency);
    currentStatementHolder.register(statement);
    return new ContextPreparedStatement(statement);
  }

  @Override
  public PreparedStatement prepareStatement(
      String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
      throws SQLException {
    PreparedStatement statement =
        delegate.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    currentStatementHolder.register(statement);
    return new ContextPreparedStatement(statement);
  }

  @Override
  public CallableStatement prepareCall(String sql) throws SQLException {
    CallableStatement statement = delegate.prepareCall(sql);
    currentStatementHolder.register(statement);
    return new ContextCallableStatement(statement);
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
      throws SQLException {
    CallableStatement statement = delegate.prepareCall(sql, resultSetType, resultSetConcurrency);
    currentStatementHolder.register(statement);
    return new ContextCallableStatement(statement);
  }

  @Override
  public CallableStatement prepareCall(
      String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability)
      throws SQLException {
    CallableStatement statement =
        delegate.prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    currentStatementHolder.register(statement);
    return new ContextCallableStatement(statement);
  }

  void closeAndClear(Statement s) throws SQLException {
    try {
      s.close();
    } finally {
      currentStatementHolder.unregister(s);
    }
  }

  void closeOnCompletionAndClear(Statement s) throws SQLException {
    try {
      s.closeOnCompletion();
    } finally {
      currentStatementHolder.unregister(s);
    }
  }

  @RequiredArgsConstructor
  class ContextStatement implements Statement {
    @Getter(AccessLevel.PROTECTED)
    @Delegate
    final Statement delegate;

    @Override
    public final void close() throws SQLException {
      closeAndClear(delegate);
    }

    @Override
    public final void closeOnCompletion() throws SQLException {
      closeOnCompletionAndClear(delegate);
    }
  }

  @RequiredArgsConstructor
  class ContextPreparedStatement implements PreparedStatement {
    @Getter(AccessLevel.PROTECTED)
    @Delegate
    final PreparedStatement delegate;

    @Override
    public final void close() throws SQLException {
      closeAndClear(delegate);
    }

    @Override
    public final void closeOnCompletion() throws SQLException {
      closeOnCompletionAndClear(delegate);
    }
  }

  @RequiredArgsConstructor
  class ContextCallableStatement implements CallableStatement {
    @Getter(AccessLevel.PROTECTED)
    @Delegate
    final CallableStatement delegate;

    @Override
    public final void close() throws SQLException {
      closeAndClear(delegate);
    }

    @Override
    public final void closeOnCompletion() throws SQLException {
      closeOnCompletionAndClear(delegate);
    }
  }
}
