@startuml

title __FACTCAST-SPRING-BOOT-AUTOCONFIGURE's Class Diagram__\n

  namespace org.factcast.spring.boot.autoconfigure.client.grpc {
    class org.factcast.spring.boot.autoconfigure.client.grpc.GrpcFactStoreAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.client.grpc {
    class org.factcast.spring.boot.autoconfigure.client.grpc.LZ4ClientAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.client.grpc {
    class org.factcast.spring.boot.autoconfigure.client.grpc.SnappyClientAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.core {
    class org.factcast.spring.boot.autoconfigure.core.FactCastAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.core {
    class org.factcast.spring.boot.autoconfigure.core.FactCastSnapshotRepositoryAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.highlevel {
    class org.factcast.spring.boot.autoconfigure.highlevel.EventCastAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.server.grpc {
    class org.factcast.spring.boot.autoconfigure.server.grpc.FactCastGrpcServerAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.server.grpc {
    class org.factcast.spring.boot.autoconfigure.server.grpc.LZ4ServerAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.server.grpc {
    class org.factcast.spring.boot.autoconfigure.server.grpc.SnappyServerAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.store.pgsql {
    class org.factcast.spring.boot.autoconfigure.store.pgsql.PgFactStoreAutoConfiguration {
    }
  }
  

  namespace org.factcast.spring.boot.autoconfigure.store.pgsql {
    namespace rds {
      class org.factcast.spring.boot.autoconfigure.store.pgsql.rds.RdsAutoConfiguration {
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
