@startuml

title __CONV's Class Diagram__\n

  namespace org.factcast.grpc.api {
    namespace conv {
      class org.factcast.grpc.api.conv.IdAndVersion {
          - uuid : UUID
          - version : int
          + IdAndVersion()
          + equals()
          + hashCode()
          + toString()
          + uuid()
          + version()
      }
    }
  }
  

  namespace org.factcast.grpc.api {
    namespace conv {
      class org.factcast.grpc.api.conv.ProtoConverter {
          {static} - EMPTY : MSG_Empty
          + ProtoConverter()
          + createCatchupNotification()
          + createCompleteNotification()
          + createNotificationFor()
          + createNotificationFor()
          + empty()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + fromProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProto()
          + toProtoOptional()
          + toProtoOptional()
          + toProtoSnapshot()
      }
    }
  }
  

  namespace org.factcast.grpc.api {
    namespace conv {
      class org.factcast.grpc.api.conv.ProtocolVersion {
          - major : int
          - minor : int
          - patch : int
          + equals()
          + hashCode()
          + isCompatibleTo()
          + major()
          + minor()
          {static} + of()
          + patch()
          + toString()
          + withMajor()
          + withMinor()
          + withPatch()
          - ProtocolVersion()
      }
    }
  }
  

  namespace org.factcast.grpc.api {
    namespace conv {
      class org.factcast.grpc.api.conv.ServerConfig {
          - properties : Map<String, String>
          + equals()
          + hashCode()
          {static} + of()
          + properties()
          + toString()
          + version()
          - ServerConfig()
      }
    }
  }
  

  org.factcast.grpc.api.conv.ServerConfig o-- org.factcast.grpc.api.conv.ProtocolVersion : version


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
