ALTER TABLE fact
    ALTER COLUMN header SET COMPRESSION lz4,
    ALTER COLUMN payload SET COMPRESSION lz4;
ALTER TABLE transformationcache
    ALTER COLUMN header SET COMPRESSION lz4,
    ALTER COLUMN payload SET COMPRESSION lz4;
