@startuml

title __SCHEMA's Class Diagram__\n

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          class org.factcast.store.pgsql.registry.validation.schema.SchemaConflictException {
              {static} - serialVersionUID : long
              + SchemaConflictException()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          class org.factcast.store.pgsql.registry.validation.schema.SchemaKey {
              - ns : String
              - type : String
              - version : int
              + equals()
              {static} + from()
              + hashCode()
              + ns()
              {static} + of()
              + toString()
              + type()
              + version()
              - SchemaKey()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          class org.factcast.store.pgsql.registry.validation.schema.SchemaSource {
              - hash : String
              - id : String
              - ns : String
              - type : String
              - version : int
              + SchemaSource()
              + SchemaSource()
              + equals()
              + hash()
              + hash()
              + hashCode()
              + id()
              + id()
              + ns()
              + ns()
              + toKey()
              + toString()
              + type()
              + type()
              + version()
              + version()
              # canEqual()
          }
        }
      }
    }
  }
  

  namespace org.factcast.store.pgsql {
    namespace registry {
      namespace validation {
        namespace schema {
          interface org.factcast.store.pgsql.registry.validation.schema.SchemaStore {
              {abstract} + contains()
              {abstract} + get()
              {abstract} + register()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
